export enum InputType {
  HEADER = 'header',
  TITLE = 'title',
  DESC = 'desc',
  MONTH_START = 'month_start',
  MONTH_END = 'month_end',
  YEAR_START = 'year_start',
  YEAR_END = 'year_end',
  OPTIONAL_DASHED = 'optional_dashed',
  OPTIONAL_DASHED2 = 'optional_dashed2',
  OPTIONAL_DASHED3 = 'optional_dashed3',
  OPTIONAL_DASHED4 = 'optional_dashed4',
  OPTIONAL_DASHED5 = 'optional_dashed5',
  CONTACT = 'contact',
  CONTACT_PERSON = 'contact_person',
  CONTACT_INFO = 'contact_info',
  CONTENT_BULLET = 'content_bullet',
}
