export enum InputType {
  header = 'header',
  title = 'title',
  desc = 'desc',
  monthStart = 'month_start',
  monthEnd = 'month_end',
  yearStart = 'year_start',
  yearEnd = 'year_end',
  optionalDashed = 'optional_dashed',
  optionalDashed2 = 'optional_dashed2',
  optionalDashed3 = 'optional_dashed3',
  optionalDashed4 = 'optional_dashed4',
  optionalDashed5 = 'optional_dashed5',
  contact = 'contact',
  contactPerson = 'contact_person',
  contactInfo = 'contact_info',
  contentBullet = 'content_bullet',
}
